package com.fox.web.domain;

public class HomeworkFB {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_fb.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_fb.my_id
     *
     * @mbg.generated
     */
    private Integer myId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_fb.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_fb.homework_id
     *
     * @mbg.generated
     */
    private Integer homeworkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_fb.level_flag
     *
     * @mbg.generated
     */
    private String levelFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_fb.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_fb.id
     *
     * @return the value of homework_fb.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_fb.id
     *
     * @param id the value for homework_fb.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_fb.my_id
     *
     * @return the value of homework_fb.my_id
     *
     * @mbg.generated
     */
    public Integer getMyId() {
        return myId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_fb.my_id
     *
     * @param myId the value for homework_fb.my_id
     *
     * @mbg.generated
     */
    public void setMyId(Integer myId) {
        this.myId = myId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_fb.user_id
     *
     * @return the value of homework_fb.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_fb.user_id
     *
     * @param userId the value for homework_fb.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_fb.homework_id
     *
     * @return the value of homework_fb.homework_id
     *
     * @mbg.generated
     */
    public Integer getHomeworkId() {
        return homeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_fb.homework_id
     *
     * @param homeworkId the value for homework_fb.homework_id
     *
     * @mbg.generated
     */
    public void setHomeworkId(Integer homeworkId) {
        this.homeworkId = homeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_fb.level_flag
     *
     * @return the value of homework_fb.level_flag
     *
     * @mbg.generated
     */
    public String getLevelFlag() {
        return levelFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_fb.level_flag
     *
     * @param levelFlag the value for homework_fb.level_flag
     *
     * @mbg.generated
     */
    public void setLevelFlag(String levelFlag) {
        this.levelFlag = levelFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_fb.mark
     *
     * @return the value of homework_fb.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_fb.mark
     *
     * @param mark the value for homework_fb.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark;
    }
}