package com.fox.web.domain;

import java.util.Date;

public class Homework {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.user_id
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.class_id
     *
     * @mbg.generated
     */
    private Integer classId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.lesson_id
     *
     * @mbg.generated
     */
    private Integer lessonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.homework_file_path
     *
     * @mbg.generated
     */
    private String homeworkFilePath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.homework_file_name
     *
     * @mbg.generated
     */
    private String homeworkFileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.correct_flag
     *
     * @mbg.generated
     */
    private Byte correctFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.star_count
     *
     * @mbg.generated
     */
    private Integer starCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.negative_count
     *
     * @mbg.generated
     */
    private Integer negativeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework.best_flag
     *
     * @mbg.generated
     */
    private Boolean bestFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.id
     *
     * @return the value of homework.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.id
     *
     * @param id the value for homework.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.user_id
     *
     * @return the value of homework.user_id
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.user_id
     *
     * @param userId the value for homework.user_id
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.class_id
     *
     * @return the value of homework.class_id
     *
     * @mbg.generated
     */
    public Integer getClassId() {
        return classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.class_id
     *
     * @param classId the value for homework.class_id
     *
     * @mbg.generated
     */
    public void setClassId(Integer classId) {
        this.classId = classId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.lesson_id
     *
     * @return the value of homework.lesson_id
     *
     * @mbg.generated
     */
    public Integer getLessonId() {
        return lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.lesson_id
     *
     * @param lessonId the value for homework.lesson_id
     *
     * @mbg.generated
     */
    public void setLessonId(Integer lessonId) {
        this.lessonId = lessonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.homework_file_path
     *
     * @return the value of homework.homework_file_path
     *
     * @mbg.generated
     */
    public String getHomeworkFilePath() {
        return homeworkFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.homework_file_path
     *
     * @param homeworkFilePath the value for homework.homework_file_path
     *
     * @mbg.generated
     */
    public void setHomeworkFilePath(String homeworkFilePath) {
        this.homeworkFilePath = homeworkFilePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.homework_file_name
     *
     * @return the value of homework.homework_file_name
     *
     * @mbg.generated
     */
    public String getHomeworkFileName() {
        return homeworkFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.homework_file_name
     *
     * @param homeworkFileName the value for homework.homework_file_name
     *
     * @mbg.generated
     */
    public void setHomeworkFileName(String homeworkFileName) {
        this.homeworkFileName = homeworkFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.create_date
     *
     * @return the value of homework.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.create_date
     *
     * @param createDate the value for homework.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.correct_flag
     *
     * @return the value of homework.correct_flag
     *
     * @mbg.generated
     */
    public Byte getCorrectFlag() {
        return correctFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.correct_flag
     *
     * @param correctFlag the value for homework.correct_flag
     *
     * @mbg.generated
     */
    public void setCorrectFlag(Byte correctFlag) {
        this.correctFlag = correctFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.star_count
     *
     * @return the value of homework.star_count
     *
     * @mbg.generated
     */
    public Integer getStarCount() {
        return starCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.star_count
     *
     * @param starCount the value for homework.star_count
     *
     * @mbg.generated
     */
    public void setStarCount(Integer starCount) {
        this.starCount = starCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.negative_count
     *
     * @return the value of homework.negative_count
     *
     * @mbg.generated
     */
    public Integer getNegativeCount() {
        return negativeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.negative_count
     *
     * @param negativeCount the value for homework.negative_count
     *
     * @mbg.generated
     */
    public void setNegativeCount(Integer negativeCount) {
        this.negativeCount = negativeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework.best_flag
     *
     * @return the value of homework.best_flag
     *
     * @mbg.generated
     */
    public Boolean getBestFlag() {
        return bestFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework.best_flag
     *
     * @param bestFlag the value for homework.best_flag
     *
     * @mbg.generated
     */
    public void setBestFlag(Boolean bestFlag) {
        this.bestFlag = bestFlag;
    }
}