package com.fox.web.mapper;

import homework9.domain.HomeworkFB;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface HomeworkFBMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_fb
     *
     * @mbg.generated
     */
    @Delete({
        "delete from homework_fb",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_fb
     *
     * @mbg.generated
     */
    @Insert({
        "insert into homework_fb (id, my_id, ",
        "user_id, homework_id, ",
        "level_flag, mark)",
        "values (#{id,jdbcType=INTEGER}, #{myId,jdbcType=INTEGER}, ",
        "#{userId,jdbcType=INTEGER}, #{homeworkId,jdbcType=INTEGER}, ",
        "#{levelFlag,jdbcType=CHAR}, #{mark,jdbcType=VARCHAR})"
    })
    int insert(HomeworkFB record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_fb
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, my_id, user_id, homework_id, level_flag, mark",
        "from homework_fb",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="my_id", property="myId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="homework_id", property="homeworkId", jdbcType=JdbcType.INTEGER),
        @Result(column="level_flag", property="levelFlag", jdbcType=JdbcType.CHAR),
        @Result(column="mark", property="mark", jdbcType=JdbcType.VARCHAR)
    })
    HomeworkFB selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_fb
     *
     * @mbg.generated
     */
    @Select({
        "select",
        "id, my_id, user_id, homework_id, level_flag, mark",
        "from homework_fb"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="my_id", property="myId", jdbcType=JdbcType.INTEGER),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.INTEGER),
        @Result(column="homework_id", property="homeworkId", jdbcType=JdbcType.INTEGER),
        @Result(column="level_flag", property="levelFlag", jdbcType=JdbcType.CHAR),
        @Result(column="mark", property="mark", jdbcType=JdbcType.VARCHAR)
    })
    List<HomeworkFB> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_fb
     *
     * @mbg.generated
     */
    @Update({
        "update homework_fb",
        "set my_id = #{myId,jdbcType=INTEGER},",
          "user_id = #{userId,jdbcType=INTEGER},",
          "homework_id = #{homeworkId,jdbcType=INTEGER},",
          "level_flag = #{levelFlag,jdbcType=CHAR},",
          "mark = #{mark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(HomeworkFB record);
}